-- Migration 004: fundamental-analysis (news/catalyst) layer + point-in-time log.
-- Run in the Supabase SQL editor. Idempotent.

-- Append-only point-in-time log: ONE ROW PER (symbol, pipeline run). This is the
-- leak-free corpus the FA backtest will replay later (accumulate-forward). Never
-- upsert/overwrite — every run inserts new rows so history is preserved with the
-- exact catalyst read + price that were knowable at that moment.
create table if not exists public.fa_snapshots (
    id            bigint generated by default as identity primary key,
    run_date      timestamptz not null default now(),
    symbol        text not null,
    name          text,
    price         double precision,   -- price at snapshot (for forward-return calc)
    fa_score      double precision,   -- sentiment * magnitude, in [-1, 1]
    sentiment     double precision,   -- net bullish(+)/bearish(-), [-1, 1]
    magnitude     double precision,   -- how market-moving, [0, 1]
    catalyst      text,               -- short label, or 'none'
    fa_confidence text,               -- High | Medium | Low
    fa_summary    text,
    fa_sources    jsonb
);
create index if not exists fa_snapshots_symbol_date
    on public.fa_snapshots (symbol, run_date desc);

-- Current-snapshot FA columns on candidates (for the live dashboard).
alter table public.candidates add column if not exists fa_score      double precision;
alter table public.candidates add column if not exists sentiment     double precision;
alter table public.candidates add column if not exists catalyst      text;
alter table public.candidates add column if not exists fa_summary    text;
alter table public.candidates add column if not exists fa_confidence text;
alter table public.candidates add column if not exists fa_sources    jsonb;
